/*
	股:id=2,	中心丝:id=3,	第一层丝的丝1:id=6
	油脂:id=5	1次捻股的丝1:id=6		1次捻股的油脂:id=7
	2次捻股的丝1:id=8 	2次捻股的油脂:id=9	第二层丝的丝1:id=10
	第二层丝的丝2:id=11	第三层丝的丝1:id=12	第三层的丝2:id=13
	第四层丝的丝1:id=14	第3次捻股的丝1:id=15	第3次捻股的油脂:id=16
	纤维芯:id=17	第1次捻股的纤维芯:id=18

	第1次捻股:id=40	第2次捻股:id=41 第3次捻股:id=42
	第一层丝:20	第二层丝:id=21  第三层丝:id=22 第四层丝:id=23

	成品丝:id=25	胚料:id=26
*/

var strand = {
	//1*7型分解
	type1:[
		{
			text:"股",
	        type:"folder",
	        name:"g1",
	        is_single_strand:"true",
	        children:[
	           {
	                text:"中心丝",
	                type:"folder",
	                name:"zxs",
	                id:"3",
	                sxfss:"1"
	           },
	           {
	           		text:"第一层丝",
	           		type:"folder",
	           		name:"sdc1",
	           		num:"6",
	           		children:[
	           			{
		           			text:"丝1",
		           			type:"folder",
		           			name:"s1",
		           			id:"4",
		           			sxfss:"1"
	           			}
	           		],
	           		id:"20"
	           },
	           {
	           		text:"油脂",
	           		type:"folder",
	           		name:"yz",
	           		id:"5"
	           }
	        ],
	        nzcs:"1",
	        id:"2",
	        sxfss:"1"
		}
	],
	//1*19分解
	type2:[
		{
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"1次捻股",
					type:"folder",
					name:"ng1",
					children:[
						{
							text:"中心丝",
							type:"folder",
							name:"zxs",
							id:"3",
							sxfss:"1"
						},
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"4",
							sxfss:"1"
						},
						{
							text:"油脂",
							type:"folder",
							name:"yz",
							id:"5"
						}
					],
					id:"40",
					sxfss:"1"
				},
				{
					text:"丝1",
					type:"folder",
					name:"s1",
					num:"12",
					id:"6",
					sxfss:"1"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"7"
				}
			],
			nzcs:"2",
			id:"2",
			sxfss:"1"	
		}
	],
	//1*37分解
	type3:[
		{
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"2次捻股",
					type:"folder",
					name:"ng2",
					children:[
						{
							text:"1次捻股",
							type:"folder",
							name:"ng1",
							children:[
								{
									text:"中心丝",
									type:"folder",
									name:"zxs",
									id:"3",
									sxfss:"1"
								},
								{
									text:"丝1",
									type:"folder",
									name:"s1",
									num:"6",
									id:"4",
									sxfss:"1"
								},
								{
									text:"油脂",
									type:"folder",
									name:"yz",
									id:"5"
								}
							],
							id:"40",
							sxfss:"1"
						},
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"12",
							id:"6",
							sxfss:"1"
						},
						{
							text:"油脂",
							type:"folder",
							name:"yz",
							id:"7"
						}
					],
					id:"41",
					sxfss:"1"
				},
				{
					text:"丝1",
					type:"folder",
					name:"s1",
					num:"18",
					id:"8",
					sxfss:"1"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"9"
				}
			],
			nzcs:"3",
			id:"2",
			sxfss:"1"	
		}
	],
	//1*9W
	type4:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

			 {
			 	text:"第一层丝",
			 	type:"folder",
			 	name:"sdc1",
			 	children:[
			 		{
			 			text:"丝1",
			 			type:"folder",
			 			name:"s1",
			 			num:"3",
			 			id:"4",
			 			sxfss:"1"
			 		}
			 	],
			 	id:"20"
			 },
			 {
			 	text:"第二层丝",
			 	type:"folder",
			 	name:"sdc2",
			 	children:[
			 		{
			 			text:"丝1",
			 			type:"folder",
			 			name:"s1",
			 			num:"3",
			 			id:"10",
			 			sxfss:"1"
			 		},
			 		{
			 			text:"丝2",
			 			type:"folder",
			 			name:"s2",
			 			num:"3",
			 			id:"11",
			 			sxfss:"1"
			 		}
			 	],
			 	id:"21"
			 },
			 {
			 	text:"油脂",
			 	type:"folder",
			 	name:"yz",
			 	id:"5"
			 }
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*19S
	type5:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"9",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"9",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*25Fi
	type6:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6Fi",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"12",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*26WS
	type7:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"5",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"5",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"5",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"10",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*31WS
	type8:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"6",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"12",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*29Fi
	type9:[
		{	
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"7",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"7F",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"14",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*36WS
	type10:[
		{	
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"7",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"7",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"7",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"14",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*37S(点线接触)
	type11:[
		{
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"15",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"15",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*41WS
	type12:[
		{	
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"8",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"16",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*49SWS
	type13:[
		{	
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"12",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"8",
							id:"13",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*55SWS
	type14:[
		{	
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"9",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"9",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"9",
							id:"12",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"9",
							id:"13",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"第四层丝",
					type:"folder",
					name:"sdc4",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"18",
							id:"14",
							sxfss:"1"
						}
					],
					id:"23"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*61
	type15:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"第三次捻股",
					type:"folder",
					name:"ng3",
					children:[
						{
							text:"第二次捻股",
							type:"folder",
							name:"ng2",
							children:[
								{
									text:"第一次捻股",
									type:"folder",
									name:"ng1",
									children:[
										{
											text:"中心丝",
											type:"folder",
											name:"zxs",
											id:"3",
											sxfss:"1"
										},
										{
											text:"丝1",
											type:"folder",
											name:"s1",
											num:"6",
											id:"4",
											sxfss:"1"
										},
										{
											text:"油脂",
											type:"folder",
											name:"yz",
											id:"5"
										}
									],
									id:"40",
									sxfss:"1"
								},
								{
									text:"丝1",
									type:"folder",
									name:"s1",
									num:"12",
									id:"6",
									sxfss:"1"
								},
								{
									text:"油脂",
									type:"folder",
									name:"yz",
									id:"7"
								}
							],
							id:"41",
							sxfss:"1"
						},
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"18",
							id:"8",
							sxfss:"1"
						},
						{
							text:"油脂",
							type:"folder",
							name:"yz",
							id:"9"
						}
					],
					id:"42",
					sxfss:"1"
				},
				{
					text:"丝1",
					type:"folder",
					name:"s1",
					num:"24",
					id:"15",
					sxfss:"1"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"16"
				}
			],
			nzcs:"4",
			id:"2",
			sxfss:"1"
		}
	],
	//1*19W
	type16:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"6",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"6",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*12
	type17:[
		{		
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"纤维芯",
					type:"folder",
					name:"xwx",
					value:"FC",
					id:"17"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"12",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*24
	type18:[
		{

			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[

				{
					text:"第一次捻股",
					type:"folder",
					name:"ng1",
					children:[
						{
							text:"纤维芯",
							type:"folder",
							name:"xwx",
							value:"FC",
							id:"17"
						},
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"9",
							id:"4",
							sxfss:"1"
						},
						{
							text:"油脂",
							type:"folder",
							name:"yz",
							id:"5"
						}
					],
					id:"40",
					sxfss:"1"
				},
				{
					text:"丝1",
					type:"folder",
					name:"s1",
					num:"15",
					id:"6",
					sxfss:"1"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"7"
				}
			],
			nzcs:"2",
			id:"2",
			sxfss:"1"
		}
	],
	//1*24S
	type19:[
		{	
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"纤维芯",
					type:"folder",
					name:"xwx",
					value:"FC",
					id:"17"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"12",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"12",
							id:"10",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*24W
	type20:[
		{
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"纤维芯",
					type:"folder",
					name:"xwx",
					value:"FC",
					id:"17"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"8",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"8",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*15
	type21:[
		{
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"纤维芯",
					type:"folder",
					name:"xwx",
					value:"FC",
					id:"17"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"15",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	],
	//1*37WS
	type22:[
		{		
			text:"股",
			type:"folder",
			name:"g1",
			is_single_strand:"true",
			children:[
				{
					text:"中心丝",
					type:"folder",
					name:"zxs",
					id:"3",
					sxfss:"1"
				},
				{
					text:"第一层丝",
					type:"folder",
					name:"sdc1",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"7",
							id:"4",
							sxfss:"1"
						}
					],
					id:"20"
				},
				{
					text:"第二层丝",
					type:"folder",
					name:"sdc2",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"7",
							id:"10",
							sxfss:"1"
						},
						{
							text:"丝2",
							type:"folder",
							name:"s2",
							num:"7",
							id:"11",
							sxfss:"1"
						}
					],
					id:"21"
				},
				{
					text:"第三层丝",
					type:"folder",
					name:"sdc3",
					children:[
						{
							text:"丝1",
							type:"folder",
							name:"s1",
							num:"14",
							id:"12",
							sxfss:"1"
						}
					],
					id:"22"
				},
				{
					text:"油脂",
					type:"folder",
					name:"yz",
					id:"5"
				}
			],
			nzcs:"1",
			id:"2",
			sxfss:"1"
		}
	]

	
}

var commonData = {
	//2 股
	kinds1:[
		{
            name:"ddh", 
            value: ""
        }, 
        {
            name:"cpbh", 
            value: ""
        }, 
        {
            name:"lb", 
            value: ""
        }, 
        {
            name:"yt", 
            value: ""
        }, 
        {
            name:"gg", 
            value: ""
        }, 
        {
            name:"zj", 
            value: ""
        }, 
        {
            name:"djmc", 
            value: ""
        }, 
        {
            name:"js", 
            value: ""
        }, 
        {
            name:"ckzzl", 
            value: ""
        }, 
        {
            name:"qd", 
            value: ""
        }, 
        {
            name:"nx", 
            value: ""
        }, 
        {
            name:"tyfs", 
            value: ""
        }, 
        {
            name:"bzfs", 
            value: ""
        }, 
        {
            name:"tsyq", 
            value: ""
        }, 
        {
            name:"nj", 
            value: ""
        }, 
        {
            name:"jjcd", 
            value: ""
        }, 
        {
            name:"zmc", 
            value: ""
        }, 
        {
            name:"lpxh", 
            value: ""
        }
	],
	//4 丝1
	kinds2:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//3 中心丝
	kinds3:[
		{
            name:"gg.lb", 
            value: ""
        }, 
        {
            name:"gg.qd", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"yl.gs", 
            value: ""
        }, 
        {
            name:"yl.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.js", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value: ""
        }
	],
	//5 油脂
	kinds4:[
		{
            name: "gg.xh", 
            value : ""
        }, 
        {
            name: "yl.tyfs", 
            value : ""
        }, 
        {
            name: "yl.dh", 
            value : ""
        }, 
        {
            name: "yl.zl", 
            value : ""
        }
	],
	//17 纤维芯
	kinds5:[
		{
            name: "gg.lb", 
            value : ""
        }, 
        {
            name: "gg.nx", 
            value : ""
        }, 
        {
            name: "gg.zj", 
            value : ""
        }, 
        {
            name: "gg.hyl", 
            value : ""
        }, 
        {
            name: "yl.gymcxs", 
            value : ""
        }, 
        {
            name: "yl.zmc", 
            value : ""
        }, 
        {
            name: "yl.dh", 
            value : ""
        }, 
        {
            name: "yl.zl", 
            value : ""
        }
	],
	// 丝2
	kinds6:[
		{
            name:"gg.lb", 
            value: ""
        }, 
        {
            name:"gg.qd", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"yl.gs", 
            value: ""
        }, 
        {
            name:"yl.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.js", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value: ""
        }
	],
	//40 1次捻股
	kinds7:[
		{
            name:"gg.qd", 
            value: ""
        }, 
        {
            name:"gg.jg", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"gg.nx", 
            value: ""
        }, 
        {
            name:"gg.tyfs", 
            value: ""
        }, 
        {
            name:"gg.nj", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.js", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value: ""
        }
	],
	//44 1zzzzz次捻股
	kinds8:[
		{
            name:"gg.lb", 
            value: ""
        }, 
        {
            name:"gg.qd", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"yl.gs", 
            value: ""
        }, 
        {
            name:"yl.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.js", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value: ""
        }
	],
	// 丝
	kinds9:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//1次捻股的丝1
	kinds10:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//2次捻股丝1
	kinds11:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//2次捻股的油脂
	kinds12:[
		{
            name: "gg.xh", 
            value : ""
        }, 
        {
            name: "yl.tyfs", 
            value : ""
        }, 
        {
            name: "yl.dh", 
            value : ""
        }, 
        {
            name: "yl.zl", 
            value : ""
        }
	],
	//2次捻股
	kinds13:[
		{
            name:"gg.qd", 
            value: ""
        }, 
        {
            name:"gg.jg", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"gg.nx", 
            value: ""
        }, 
        {
            name:"gg.tyfs", 
            value: ""
        }, 
        {
            name:"gg.nj", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.js", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value: ""
        }
	],
	//第一层丝下的丝1
	kinds14:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//第二层丝的丝1
	kinds15:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//第二层丝的丝2
	kinds16:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//第三层丝的丝1
	kinds17:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//第三层丝的丝2
	kinds18:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//第四层丝的丝1
	kinds19:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//3次捻股丝1
	kinds20:[
		{
            name:"gg.lb", 
            value:""
        }, 
        {
            name:"gg.qd", 
            value:""
        }, 
        {
            name:"gg.zj", 
            value:""
        }, 
        {
            name:"yl.gs", 
            value:""
        }, 
        {
            name:"yl.gymcxs", 
            value:""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value:""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.js", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value:""
        }, 
        {
            name:"yl.sxfs1.zzl", 
            value:""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value:""
        }
	],
	//3次捻股的油脂
	kinds21:[
		{
            name: "gg.xh", 
            value : ""
        }, 
        {
            name: "yl.tyfs", 
            value : ""
        }, 
        {
            name: "yl.dh", 
            value : ""
        }, 
        {
            name: "yl.zl", 
            value : ""
        }
	],
	//3次捻股
	kinds22:[
		{
            name:"gg.qd", 
            value: ""
        }, 
        {
            name:"gg.jg", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"gg.nx", 
            value: ""
        }, 
        {
            name:"gg.tyfs", 
            value: ""
        }, 
        {
            name:"gg.nj", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.dc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.ds", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.djmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.js", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.zmc", 
            value: ""
        }, 
        {
            name:"yl.sxfs1.gzlxh", 
            value: ""
        }
	],
	//纤维芯
	kinds23:[
		{
            name:"gg.lb", 
            value: ""
        }, 
        {
            name:"gg.nx", 
            value: ""
        }, 
        {
            name:"gg.zj", 
            value: ""
        }, 
        {
            name:"gg.hyl", 
            value: ""
        }, 
        {
            name:"yl.gymcxs", 
            value: ""
        }, 
        {
            name:"yl.zmc", 
            value: ""
        }, 
        {
            name:"yl.dh", 
            value: ""
        }, 
        {
            name:"yl.zl", 
            value: ""
        }
	]
}

strand.strandDataFun = function (thisData,thisSpec,children){
		//=============股===================
		var strandArray = commonData.kinds1;
		//订单号
		strandArray[0].value=children.ddh;
		//产品编号
		strandArray[1].value=children.cpbh;
		//类别
		strandArray[2].value=children.product_category;
		//用途
		strandArray[3].value=children.purpose;
		//规格
		strandArray[4].value=children.spec;
		//直径
		strandArray[5].value=children.diameter;
		//单件米长
		strandArray[6].value=children.length;
		//件数
		strandArray[7].value=children.count;
		//参考总重量
		strandArray[8].value="";
		//强度
		strandArray[9].value=children.strength;
		//捻向
		strandArray[10].value=children.direction;
		//涂油方式
		strandArray[11].value=children.oil_method;
		//包装方式
		strandArray[12].value=children.package_method;
		//特殊要求
		strandArray[13].value=children.special_need;
		//捻距
		strandArray[14].value="";
		//jjcd
		strandArray[15].value="";
		//总米长
		strandArray[16].value=Number(children.length)*Number(children.count);
		//轮盘型号
		strandArray[17].value="";

		//==================丝===================
		var silk = commonData.kinds2;
		var onebeyoudSilk = commonData.kinds14;//第一层丝的丝1
		var TwobeyoundSilk1 = commonData.kinds15;//第二层丝的丝1
		var TwobeyoundSilk2 = commonData.kinds16;//第二层丝的丝2
		var ThreebeyoundSilk1 = commonData.kinds17;//第三层丝的丝1
		var ThreebeyoundSilk2 = commonData.kinds18;//第三层丝的丝2
		var FourbeyoundSilk = commonData.kinds19;//第四层丝的丝1
		var silk1 = commonData.kinds10;//1次捻股丝1
		var silk2 = commonData.kinds11;//2次捻股丝1
		var silk3 = commonData.kinds20;//3次捻股丝1
		//丝-类别
		silk[0].value=children.product_category;
		silk1[0].value=children.product_category;
		silk2[0].value=children.product_category;
		silk3[0].value=children.product_category;
		onebeyoudSilk[0].value=children.product_category;
		TwobeyoundSilk1[0].value=children.product_category;
		TwobeyoundSilk2[0].value=children.product_category;
		ThreebeyoundSilk1[0].value=children.product_category;
		ThreebeyoundSilk2[0].value=children.product_category;
		FourbeyoundSilk[0].value=children.product_category;
		//丝-强度
		silk[1].value=children.strength;
		silk1[1].value=children.strength;
		silk2[1].value=children.strength;
		silk3[1].value=children.strength;
		onebeyoudSilk[1].value=children.strength;
		TwobeyoundSilk1[1].value=children.strength;
		TwobeyoundSilk2[1].value=children.strength;
		ThreebeyoundSilk1[1].value=children.strength;
		ThreebeyoundSilk2[1].value=children.strength;
		FourbeyoundSilk[1].value=children.strength;
		//丝-直径  空

		//丝-根数
		// var first_silk = children.strand_first_floor;
		// var second_silk = children.strand_second_floor;
		// var third_silk = children.strand_third_floor;
		// var fourth_silk = children.strand_fourth_floor;

		//41-丝
		var secondSilk = commonData.kinds9;
		//丝-类别
		secondSilk[0].value=children.product_category;
		//丝-强度
		secondSilk[1].value=children.strength;

		//===================中心丝===============================a
		var center_wire = commonData.kinds3;

		center_wire[0].value=children.product_category;
		center_wire[1].value=children.strength;
		//center_wire[3].value=result.center_wire;

		//===================油脂================================
		var grease = commonData.kinds4;
		var grease1 = commonData.kinds4; //1次捻股的油脂
		var grease2 = commonData.kinds12; //2次捻股的油脂
		var grease3 = commonData.kinds21; //3次捻股的油脂
		grease[1].value=children.oil_method;
		grease1[1].value=children.oil_method;
		grease2[1].value=children.oil_method;
		grease3[1].value=children.oil_method;

		//==================一次捻股============================
		var firstNg = commonData.kinds7;

		//==================二次捻股============================
		var secondNg = commonData.kinds13;

		//==================三次捻股============================

		var thirdNg = commonData.kinds22;

		//==================纤维芯=============================
		var core = commonData.kinds23;

	switch(thisSpec){
		case "1*7":
			center_wire[3].value="1";
			silk[3].value="6";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":silk,
				"5":grease
			};
			return sendData;
			break;
		case "1*19":
			center_wire[3].value="1";
			silk[3].value="6";
			silk1[3].value="12";
			firstNg[0].value=children.strength;
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":silk,
				"5":grease,
				"6":silk1,				
				"7":grease1,
				"40":firstNg
			};
			return sendData;
			break;
		case "1*37":
			center_wire[3].value="1";
			silk[3].value="6";
			silk1[3].value="12";
			silk2[3].value="18";
			firstNg[0].value=children.strength;
			secondNg[0].value=children.strength;
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":silk,
				"5":grease,
				"6":silk1,
				"7":grease1,
				"8":silk2,
				"9":grease2,
				"40":firstNg,
				"41":secondNg
			};
			return sendData;
			break;
		case "1*9W":
			onebeyoudSilk[3].value="3";
			TwobeyoundSilk1[3].value="3";
			TwobeyoundSilk2[3].value="3";
			var sendData = {
				"2":strandArray,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2
			};
			return sendData;
			break;
		case "1*19S":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="9";
			TwobeyoundSilk1[3].value="9";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1
			};
			return sendData;
			break;
		case "1*25Fi":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="6";
			TwobeyoundSilk1[3].value="6Fi";
			ThreebeyoundSilk1[3].value="12";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*26WS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="5";
			TwobeyoundSilk1[3].value="5";
			TwobeyoundSilk2[3].value="5";
			ThreebeyoundSilk1[3].value="10";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*31WS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="6";
			TwobeyoundSilk1[3].value="6";
			TwobeyoundSilk2[3].value="6";
			ThreebeyoundSilk1[3].value="12";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*29Fi":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="7";
			TwobeyoundSilk1[3].value="7F";
			ThreebeyoundSilk1[3].value="14";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*36WS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="7";
			TwobeyoundSilk1[3].value="7";
			TwobeyoundSilk2[3].value="7";
			ThreebeyoundSilk1[3].value="14";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*37S":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="6";
			TwobeyoundSilk1[3].value="15";
			ThreebeyoundSilk1[3].value="15";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*41WS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="8";
			TwobeyoundSilk1[3].value="8";
			TwobeyoundSilk2[3].value="8";
			ThreebeyoundSilk1[3].value="16";
			var sendData = {	
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
		case "1*49SWS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="8";
			TwobeyoundSilk1[3].value="8";
			ThreebeyoundSilk1[3].value="8";
			ThreebeyoundSilk2[3].value="8";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"12":ThreebeyoundSilk1,
				"13":ThreebeyoundSilk2,
			};
			return sendData;
			break;
		case "1*55SWS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="9";
			TwobeyoundSilk1[3].value="9";
			ThreebeyoundSilk1[3].value="9";
			ThreebeyoundSilk2[3].value="9";
			FourbeyoundSilk[3].value="18";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"12":ThreebeyoundSilk1,
				"13":ThreebeyoundSilk2,
				"14":FourbeyoundSilk
			};
			return sendData;
			break;
		case "1*61":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="6";
			silk1[3].value="12";
			silk2[3].value="18";
			silk3[3].value="24";
			firstNg[0].value=children.strength;
			secondNg[0].value=children.strength;
			thirdNg[0].value=children.strength;
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"6":silk1,
				"7":grease1,
				"8":silk2,
				"9":grease2,
				"15":silk3,
				"16":grease3,
				"40":firstNg,
				"41":secondNg,
				"42":thirdNg
			};
			return sendData;
			break;
		case "1*19W":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="6";
			TwobeyoundSilk1[3].value="6";
			TwobeyoundSilk2[3].value="6";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2
			};
			return sendData;
			break;
		case "1*12":
			onebeyoudSilk[3].value="12";
			var sendData = {
				"2":strandArray,
				"4":onebeyoudSilk,
				"5":grease,
				"17":core
			}
			return sendData;
			break;
		case "1*24":
			onebeyoudSilk[3].value="9";
			silk1[3].value="15";
			firstNg[0].value=children.strength;
			var sendData = {
				"2":strandArray,
				"4":onebeyoudSilk,
				"5":grease,
				"6":silk1,
				"7":grease1,
				"17":core,
				"40":firstNg
			};
			return sendData;
			break;
		case "1*24S":
			onebeyoudSilk[3].value="12";
			TwobeyoundSilk1[3].value="12";
			var sendData = {
				"2":strandArray,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"17":core
			};
			return sendData;
			break;

		case "1*24W":
			onebeyoudSilk[3].value="8";
			TwobeyoundSilk1[3].value="8";
			TwobeyoundSilk2[3].value="8";
			var sendData = {
				"2":strandArray,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2,
				"17":core
			};
			return sendData;
			break;

		case "1*15":
			onebeyoudSilk[3].value="15";
			var sendData = {
				"2":strandArray,
				"4":onebeyoudSilk,
				"5":grease,
				"17":core	
			};
			return sendData;
			break;

		case "1*37WS":
			center_wire[3].value="1";
			onebeyoudSilk[3].value="7";
			TwobeyoundSilk1[3].value="7";
			TwobeyoundSilk2[3].value="7";
			ThreebeyoundSilk1[3].value="14";
			var sendData = {
				"2":strandArray,
				"3":center_wire,
				"4":onebeyoudSilk,
				"5":grease,
				"10":TwobeyoundSilk1,
				"11":TwobeyoundSilk2,
				"12":ThreebeyoundSilk1
			};
			return sendData;
			break;
	}
		 
}

strand.cpsStruct = [
	{
		text:"成品丝",
		type:"folder",
		name:"cps",
		is_cps:"true",
		children:[
			{
				text:"胚料",
				type:"folder",
				name:"pl",
				id:"26"
			}
		],
		id:"25",
		sxfss:"1"
	}
];
//成品丝
strand.cpsDataFun = function(children){
	var strandArray = commonData.kinds1;
	//订单号
	strandArray[0].value=children.ddh;
	//产品编号
	strandArray[1].value=children.cpbh;
	//类别
	strandArray[2].value=children.product_category;
	//用途
	strandArray[3].value=children.purpose;
	//规格
	strandArray[4].value=children.spec;
	//直径
	strandArray[5].value=children.diameter;
	//单件米长
	strandArray[6].value=children.length;
	//件数
	strandArray[7].value=children.count;
	//参考总重量
	strandArray[8].value="";
	//强度
	strandArray[9].value=children.strength;
	//捻向
	strandArray[10].value=children.direction;
	//涂油方式
	strandArray[11].value=children.oil_method;
	//包装方式
	strandArray[12].value=children.package_method;
	//特殊要求
	strandArray[13].value=children.special_need;
	//捻距
	strandArray[14].value="";
	//jjcd
	strandArray[15].value="";
	//总米长
	strandArray[16].value=Number(children.length)*Number(children.count);
	//轮盘型号
	strandArray[17].value="";
	var sendData = {
		//strandArray  暂时值为空
		"25":""
	}
	return sendData;
}

module.exports = strand;