module.exports = {
  "init_data": [
    {
      "collection": "internal_forms",
      "data": [
        {
          "name": "jsxjgb",
          "metal_core_structure": "1*7",
          "gc_center": "",
          "gc_wg_plies_1": 1,
          "gc_explain": "单股绳，没有合绳工序",
          "xg_center_wire": "",
          "xg_plies_1": "",
          "xg_plies_2": "",
          "xg_plies_3": "",
          "xg_structure": "",
          "zxg_nzcs": "",
          "xg_plies_explain": "",
          "wg_center_wire": 1,
          "wg_plies_1": 6,
          "wg_plies_2": "",
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_explain": "1次捻制",
          "wg_nzcs": 1,
          "wg_structure": "1+6"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "1*19",
          "gc_center": "",
          "gc_wg_plies_1": 1,
          "gc_explain": "单股绳，没有合绳工序",
          "xg_center_wire": "",
          "xg_plies_1": "",
          "xg_plies_2": "",
          "xg_plies_3": "",
          "xg_structure": "",
          "zxg_nzcs": "",
          "xg_plies_explain": "",
          "wg_center_wire": 1,
          "wg_plies_1": 6,
          "wg_plies_2": 12,
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 1,
          "wg_explain": "2次捻制",
          "wg_nzcs": 2,
          "wg_structure": "1+6+12"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "1*19S",
          "gc_center": "",
          "gc_wg_plies_1": 1,
          "gc_explain": "单股绳，没有合绳工序",
          "xg_center_wire": "",
          "xg_plies_1": "",
          "xg_plies_2": "",
          "xg_plies_3": "",
          "xg_structure": "",
          "zxg_nzcs": "",
          "xg_plies_explain": "",
          "wg_center_wire": 1,
          "wg_plies_1": 9,
          "wg_plies_2": 9,
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 1,
          "wg_explain": "1次捻制",
          "wg_nzcs": 1,
          "wg_structure": "1+9+9"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "1*19W",
          "gc_center": "",
          "gc_wg_plies_1": 1,
          "gc_explain": "单股绳，没有合绳工序",
          "xg_center_wire": "",
          "xg_plies_1": "",
          "xg_plies_2": "",
          "xg_plies_3": "",
          "xg_structure": "",
          "zxg_nzcs": "",
          "xg_plies_explain": "",
          "wg_center_wire": 1,
          "wg_plies_1": 6,
          "wg_plies_2": "6/6",
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 2,
          "wg_structure": "1+6+6/6",
          "wg_nzcs": 1,
          "wg_explain": "1次捻制"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "1*26SW",
          "gc_center": "",
          "gc_wg_plies_1": 1,
          "gc_explain": "单股绳，没有合绳工序",
          "xg_center_wire": "",
          "xg_plies_1": "",
          "xg_plies_2": "",
          "xg_plies_3": "",
          "xg_structure": "",
          "zxg_nzcs": "",
          "xg_plies_explain": "",
          "wg_center_wire": 1,
          "wg_plies_1": 5,
          "wg_plies_2": "5/5",
          "wg_plies_3": 10,
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 2,
          "wg_gg_plies_3": 1,
          "wg_structure": "1+5+5/5+10",
          "wg_nzcs": 1,
          "wg_explain": "1次捻制"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "7*7",
          "gc_center": 1,
          "gc_wg_plies_1": 6,
          "gc_explain": "",
          "xg_center_wire": 1,
          "xg_plies_1": 6,
          "xg_plies_2": "",
          "xg_plies_3": "",
          "xg_gg_center_wire": 1,
          "xg_gg_plies_1": 1,
          "xg_structure": "1+6",
          "zxg_nzcs": 1,
          "xg_plies_explain": "1次捻制",
          "wg_center_wire": 1,
          "wg_plies_1": 6,
          "wg_plies_2": "",
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_structure": "1+6",
          "wg_nzcs": 1,
          "wg_explain": "1次捻制"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "7*19",
          "gc_center": 1,
          "gc_wg_plies_1": 6,
          "gc_explain": "",
          "xg_center_wire": 1,
          "xg_plies_1": 6,
          "xg_plies_2": 12,
          "xg_plies_3": "",
          "xg_gg_center_wire": 1,
          "xg_gg_plies_1": 1,
          "xg_gg_plies_2": 1,
          "xg_structure": "1+6+12",
          "zxg_nzcs": 2,
          "xg_plies_explain": "2次捻制",
          "wg_center_wire": 1,
          "wg_plies_1": 6,
          "wg_plies_2": 12,
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 1,
          "wg_structure": "1+6+12",
          "wg_nzcs": 2,
          "wg_explain": "2次捻制"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "7*19S",
          "gc_center": 1,
          "gc_wg_plies_1": 6,
          "gc_explain": "",
          "xg_center_wire": 1,
          "xg_plies_1": 9,
          "xg_plies_2": 9,
          "xg_plies_3": "",
          "xg_gg_center_wire": 1,
          "xg_gg_plies_1": 1,
          "xg_gg_plies_2": 1,
          "xg_structure": "1+9+9",
          "zxg_nzcs": 1,
          "xg_plies_explain": "1次捻制",
          "wg_center_wire": 1,
          "wg_plies_1": 9,
          "wg_plies_2": 9,
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 1,
          "wg_structure": "1+9+9",
          "wg_nzcs": 1,
          "wg_explain": "1次捻制"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "7*19W",
          "gc_center": 1,
          "gc_wg_plies_1": 6,
          "gc_explain": "",
          "xg_center_wire": 1,
          "xg_plies_1": 6,
          "xg_plies_2": "6/6",
          "xg_plies_3": "",
          "xg_gg_center_wire": 1,
          "xg_gg_plies_1": 1,
          "xg_gg_plies_2": 2,
          "xg_structure": "1+6+6/6",
          "zxg_nzcs": 1,
          "xg_plies_explain": "1次捻制",
          "wg_center_wire": 1,
          "wg_plies_1": 6,
          "wg_plies_2": "6/6",
          "wg_plies_3": "",
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 2,
          "wg_structure": "1+6+6/6",
          "wg_nzcs": 1,
          "wg_explain": "1次捻制"
        },
        {
          "name": "jsxjgb",
          "metal_core_structure": "7*26SW",
          "gc_center": 1,
          "gc_wg_plies_1": 6,
          "gc_explain": "",
          "xg_center_wire": 1,
          "xg_plies_1": 5,
          "xg_plies_2": "5/5",
          "xg_plies_3": 10,
          "xg_gg_center_wire": 1,
          "xg_gg_plies_1": 1,
          "xg_gg_plies_2": 2,
          "xg_gg_plies_3": 1,
          "xg_structure": "1+5+5/5+10",
          "zxg_nzcs": 1,
          "xg_plies_explain": "1次捻制",
          "wg_center_wire": 1,
          "wg_plies_1": 5,
          "wg_plies_2": "5/5",
          "wg_plies_3": 10,
          "wg_gg_center_wire": 1,
          "wg_gg_plies_1": 1,
          "wg_gg_plies_2": 2,
          "wg_gg_plies_3": 1,
          "wg_structure": "1+5+5/5+10",
          "wg_nzcs": 1,
          "wg_explain": "1次捻制"
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "1*7",
          "gc_plies": "",
          "gc_plies_1": "",
          "gc_plies_2": "",
          "gc_plies_3": "",
          "ggg_plies_1": "",
          "ggg_plies_2": "",
          "ggg_plies_3": "",
          "gc_explain": "单股绳，没有合绳工序",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_plies_2": "",
          "gs_plies_3": "",
          "gs_plies_4": "",
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gsi_plies_2": "",
          "gsi_plies_3": "",
          "gsi_plies_4": "",
          "gs_explain": "1次捻制",
          "hscs": "",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "1*19",
          "gc_plies": "",
          "gc_plies_1": "",
          "gc_plies_2": "",
          "gc_plies_3": "",
          "ggg_plies_1": "",
          "ggg_plies_2": "",
          "ggg_plies_3": "",
          "gc_explain": "单股绳，没有合绳工序",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 6,
          "gs_plies_2": 12,
          "gs_structure": "1+6+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "2次捻制",
          "hscs": "",
          "nzcs": 2
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "1*37",
          "gc_plies": "",
          "gc_plies_1": "",
          "gc_plies_2": "",
          "gc_plies_3": "",
          "ggg_plies_1": "",
          "ggg_plies_2": "",
          "ggg_plies_3": "",
          "gc_explain": "单股绳，没有合绳工序",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": 12,
          "gs_plies_3": 18,
          "gs_structure": "1+6+12+18",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gs_explain": "3次捻制",
          "hscs": "",
          "nzcs": 3
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*7",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*9W",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 0,
          "gs_plies": 2,
          "gs_plies_1": "3",
          "gs_plies_2": "3/3",
          "gs_structure": "0+3+3/3",
          "gsi_plies_1": 3,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*19S",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 9,
          "gs_plies_2": 9,
          "gs_structure": "1+9+9",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*19W",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 6,
          "gs_plies_2": "6/6",
          "gs_structure": "1+6+6/6",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*25FI",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": "6F",
          "gs_plies_3": 12,
          "gs_structure": "1+6+6F+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*26WS",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 5,
          "gs_plies_2": "5/5",
          "gs_plies_3": 10,
          "gs_structure": "1+5+5/5+10",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*31WS",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": "6/6",
          "gs_plies_3": 12,
          "gs_structure": "1+6+6/6+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*19",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 6,
          "gs_plies_2": 12,
          "gs_structure": "1+6+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "2次捻制",
          "hscs": "1",
          "nzcs": 2
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*29Fi",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 7,
          "gs_plies_2": "7F",
          "gs_plies_3": 14,
          "gs_plies_4": "",
          "gs_structure": "1+7+7F+14",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gsi_plies_4": "",
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*36WS",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 7,
          "gs_plies_2": "7/7",
          "gs_plies_3": 14,
          "gs_structure": "1+7+7/7+14",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*37S",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": 15,
          "gs_plies_3": 15,
          "gs_structure": "1+6+15+15",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1,
          "comment": "点线接触"
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*41WS",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 8,
          "gs_plies_2": "8/8",
          "gs_plies_3": 16,
          "gs_structure": "1+8+8/8+16",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*49SWS",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 4,
          "gs_plies_1": 8,
          "gs_plies_2": 8,
          "gs_plies_3": "8/8",
          "gs_plies_4": 16,
          "gs_structure": "1+8+8+8/8+16",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 2,
          "gsi_plies_4": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*55SWS",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 4,
          "gs_plies_1": 9,
          "gs_plies_2": 9,
          "gs_plies_3": "9/9",
          "gs_plies_4": 18,
          "gs_structure": "1+9+9+9/9+18",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 2,
          "gsi_plies_4": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*37",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": 12,
          "gs_plies_3": 18,
          "gs_structure": "1+6+12+18",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gs_explain": "3次捻制",
          "hscs": "1",
          "nzcs": 3
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*61",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 4,
          "gs_plies_1": 6,
          "gs_plies_2": 12,
          "gs_plies_3": 18,
          "gs_plies_4": 24,
          "gs_structure": "1+6+12+18+24",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gsi_plies_4": 1,
          "gs_explain": "4次捻制",
          "hscs": "1",
          "nzcs": 4
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*19S",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 9,
          "gs_plies_2": 9,
          "gs_structure": "1+9+9",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*19W",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 6,
          "gs_plies_2": "6/6",
          "gs_structure": "1+6+6/6",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*25Fi",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": "6F",
          "gs_plies_3": 12,
          "gs_structure": "1+6+6F+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*26WS",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 5,
          "gs_plies_2": "5/5",
          "gs_plies_3": 10,
          "gs_structure": "1+5+5/5+10",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*31WS",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": "6/6",
          "gs_plies_3": 12,
          "gs_structure": "1+6+6/6+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*36WS",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 7,
          "gs_plies_2": "7/7",
          "gs_plies_3": 14,
          "gs_structure": "1+7+7/7+14",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*41WS",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 8,
          "gs_plies_2": "8/8",
          "gs_plies_3": 16,
          "gs_structure": "1+8+8/8+16",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*49SWS",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 4,
          "gs_plies_1": 8,
          "gs_plies_2": 8,
          "gs_plies_3": "8/8",
          "gs_plies_4": 16,
          "gs_structure": "1+8+8+8/8+16",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 2,
          "gsi_plies_4": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "8*55SWS",
          "gc_plies": 1,
          "gc_plies_1": 8,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 4,
          "gs_plies_1": 9,
          "gs_plies_2": 9,
          "gs_plies_3": "9/9",
          "gs_plies_4": 18,
          "gs_structure": "1+9+9+9/9+18",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 2,
          "gsi_plies_4": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "17*7",
          "gc_plies": 2,
          "gc_plies_1": 6,
          "gc_plies_2": 11,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "gc_explain": "存在2次合绳和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "18*7",
          "gc_plies": 2,
          "gc_plies_1": 6,
          "gc_plies_2": 12,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "gc_explain": "存在2次合绳和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "19*7",
          "gc_plies": 2,
          "gc_plies_1": 6,
          "gc_plies_2": 12,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "gc_explain": "存在2次合绳和1次合绳，中间的中心股因不考核归为金属芯中心股",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "18*19W",
          "gc_plies": 2,
          "gc_plies_1": 6,
          "gc_plies_2": 12,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "gc_explain": "存在2次合绳和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 6,
          "gs_plies_2": "6/6",
          "gs_structure": "1+6+6/6",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gs_explain": "1次捻制",
          "hscs": "1,2",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "18*19S",
          "gc_plies": 2,
          "gc_plies_1": 6,
          "gc_plies_2": 12,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "gc_explain": "存在2次合绳和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 9,
          "gs_plies_2": 9,
          "gs_structure": "1+9+9",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "18*19",
          "gc_plies": 2,
          "gc_plies_1": 6,
          "gc_plies_2": 12,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "gc_explain": "存在2次合绳，和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 6,
          "gs_plies_2": 12,
          "gs_structure": "1+6+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "2次捻制",
          "hscs": "1,2",
          "nzcs": 2
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "34*7",
          "gc_plies": 3,
          "gc_plies_1": 6,
          "gc_plies_2": 11,
          "gc_plies_3": 17,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "ggg_plies_3": 1,
          "gc_explain": "存在3次合绳，和2次合绳，和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2,3",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "36*7",
          "gc_plies": 3,
          "gc_plies_1": 6,
          "gc_plies_2": 12,
          "gc_plies_3": 18,
          "ggg_plies_1": 1,
          "ggg_plies_2": 1,
          "ggg_plies_3": 1,
          "gc_explain": "存在3次合绳，和2次合绳，和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2,3",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "35W*7",
          "gc_plies": 3,
          "gc_plies_1": 6,
          "gc_plies_2": "6/6",
          "gc_plies_3": 16,
          "ggg_plies_1": 1,
          "ggg_plies_2": 2,
          "ggg_plies_3": 1,
          "gc_explain": "存在3次合绳，和2次合绳，和1次合绳  中间的中心股因不考核归金属芯中心股。",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2,3",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "35W*K7",
          "gc_plies": 3,
          "gc_plies_1": 6,
          "gc_plies_2": "6/6",
          "gc_plies_3": 16,
          "ggg_plies_1": 1,
          "ggg_plies_2": 2,
          "ggg_plies_3": 1,
          "gc_explain": "存在3次合绳，和2次合绳，和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2,3",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "40W*7",
          "gc_plies": 3,
          "gc_plies_1": 7,
          "gc_plies_2": "7/7",
          "gc_plies_3": 18,
          "ggg_plies_1": 1,
          "ggg_plies_2": 2,
          "ggg_plies_3": 1,
          "gc_explain": "存在3次合绳，和2次合绳，和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2,3",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "24W*7",
          "gc_plies": 3,
          "gc_plies_1": 4,
          "gc_plies_2": "4/4",
          "gc_plies_3": 12,
          "ggg_plies_1": 1,
          "ggg_plies_2": 2,
          "ggg_plies_3": 1,
          "gc_explain": "存在3次合绳，和2次合绳，和1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 1,
          "gs_plies_1": 6,
          "gs_structure": "1+6",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1,2,3",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*12",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "7FC",
          "gs_center_wire": "",
          "gs_plies": 1,
          "gs_plies_1": 12,
          "gs_structure": "",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*24",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "7FC",
          "gs_center_wire": "",
          "gs_plies": 2,
          "gs_plies_1": 9,
          "gs_plies_2": 15,
          "gs_structure": "",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "2次捻制",
          "hscs": "1",
          "nzcs": 2
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*24S",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "7FC",
          "gs_center_wire": "",
          "gs_plies": 2,
          "gs_plies_1": 12,
          "gs_plies_2": 12,
          "gs_structure": "",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*24W",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "7FC",
          "gs_center_wire": "",
          "gs_plies": 2,
          "gs_plies_1": 8,
          "gs_plies_2": "8/8",
          "gs_structure": "",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "6*15",
          "gc_plies": 1,
          "gc_plies_1": 6,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "7FC",
          "gs_center_wire": "",
          "gs_plies": 1,
          "gs_plies_1": 15,
          "gs_structure": "",
          "gsi_plies_1": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "4*19S",
          "gc_plies": 1,
          "gc_plies_1": 4,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 2,
          "gs_plies_1": 9,
          "gs_plies_2": 9,
          "gs_structure": "1+9+9",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "4*25Fi",
          "gc_plies": 1,
          "gc_plies_1": 4,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": "6F",
          "gs_plies_3": 12,
          "gs_structure": "1+6+6F+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 1,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "4*26WS",
          "gc_plies": 1,
          "gc_plies_1": 4,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 5,
          "gs_plies_2": "5/5",
          "gs_plies_3": 10,
          "gs_structure": "1+5+5/5+10",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "4*31WS",
          "gc_plies": 1,
          "gc_plies_1": 4,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 6,
          "gs_plies_2": "6/6",
          "gs_plies_3": 12,
          "gs_structure": "1+6+6/6+12",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "4*37WS",
          "gc_plies": 1,
          "gc_plies_1": 4,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 7,
          "gs_plies_2": "7/7",
          "gs_plies_3": 14,
          "gs_structure": "1+7+7/7+14",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "name": "gssjgb",
          "wire_rope_structure": "4*41WS",
          "gc_plies": 1,
          "gc_plies_1": 4,
          "ggg_plies_1": 1,
          "gc_explain": "1次合绳",
          "gs_fiber_core": "",
          "gs_center_wire": 1,
          "gs_plies": 3,
          "gs_plies_1": 8,
          "gs_plies_2": "8/8",
          "gs_plies_3": 16,
          "gs_structure": "1+8+8/8+16",
          "gsi_plies_1": 1,
          "gsi_plies_2": 2,
          "gsi_plies_3": 1,
          "gs_explain": "1次捻制",
          "hscs": "1",
          "nzcs": 1
        },
        {
          "device_num": "223",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "224",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "224",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "225",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "226",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "227",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "228",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "229",
          "device_model": "200/6",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "239",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "240",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "241",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "242",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "210",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "209",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "215",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "216",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "217",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "218",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "219",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "220",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "221",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "222",
          "device_model": "200/18",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "312",
          "device_model": "300/12盘",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "306",
          "device_model": "300/6盘",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "406",
          "device_model": "400/6盘",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "408",
          "device_model": "400/8盘",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "409",
          "device_model": "400/9盘",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        },
        {
          "device_num": "509",
          "device_model": "500/9盘",
          "device_params": "",
          "std_capacity": "",
          "operating_rate": "",
          "fact_capacity": "",
          "fact_std_capacity": "",
          "length_error_rate": "",
          "cone_use_cycle": "",
          "total_down_time": "",
          "down_count": "",
          "total_repair_time": "",
          "twist_contraction_rate": "",
          "vender": "",
          "opened_time": "",
          "installation_site": "",
          "name": "jtb"
        }
      ]
    },
    {
      "collection": "users",
      "data": {
        "username": "admin",
        "password": "admin4now!",
        "first_name": "一",
        "last_name": "丁",
        "email": "admin@insevo.cn",
        "roles": [
          "管理员"
        ]
      }
    },
    {
      "collection": "enums",
      "data": [
        {
          "name": "roles",
          "values": [
            "生产管理部",
            "车间主任",
            "班组长",
            "质检部"
          ]
        },
        {
          "name": "orgs",
          "values": {
            "org1": [
              "一车间",
              "二车间",
              "三车间"
            ],
            "org2": [
              "一班组",
              "二班组",
              "三班组"
            ],
            "org3": [
              "班长",
              "表面处理工段",
              "粗拉工段",
              "热处理工段",
              "表面镀工段",
              "细拉工段",
              "捻股工段",
              "合绳工段"
            ]
          }
        },
        {
          "name": "perms",
          "values": [
            {
              "name": "display",
              "value": "显示"
            },
            {
              "name": "operate",
              "value": "创建/修改"
            },
            {
              "name": "approve",
              "value": "审核"
            },
            {
              "name": "assign",
              "value": "指派工单操作人员"
            },
            {
              "name": "confirm",
              "value": "确认工单完工"
            }
          ]
        },
        {
          "name": "steps",
          "values": [
            "表面处理",
            "胚料工段",
            "胚料拉拔",
            "成品丝工段",
            "成品丝拉拔",
            "热处理&镀锌",
            "捻股",
            "合绳"
          ]
        },
        {
          "name": "types",
          "values": [
            {
              "name": "order",
              "value": "生产订单",
              "order": 10,
              "display": false,
              "mixed": true,
              "steps": false,
              "perms": [
                "display",
                "operate",
                "approve"
              ]
            },
            {
              "name": "order_plan",
              "value": "订单计划",
              "order": 30,
              "display": true,
              "mixed": true,
              "steps": false,
              "perms": [
                "display",
                "operate",
                "approve"
              ]
            },
            {
              "name": "bom",
              "value": "BOM表",
              "order": 40,
              "display": false,
              "mixed": true,
              "steps": true,
              "perms": [
                "display",
                "operate",
                "approve"
              ]
            },
            {
              "name": "production_plan",
              "value": "生产计划",
              "order": 50,
              "display": true,
              "mixed": true,
              "steps": true,
              "perms": [
                "display",
                "operate",
                "approve"
              ]
            },
            {
              "name": "work_plan",
              "value": "作业计划",
              "order": 70,
              "display": true,
              "mixed": true,
              "steps": true,
              "perms": [
                "display",
                "operate",
                "approve"
              ]
            },
            {
              "name": "material_receive",
              "value": "物料领用",
              "order": 80,
              "display": true,
              "mixed": true,
              "steps": true,
              "perms": [
                "display",
                "operate",
                "approve"
              ]
            },
            {
              "name": "work_order",
              "value": "工单",
              "order": 90,
              "display": true,
              "mixed": false,
              "steps": true,
              "perms": [
                "display",
                "operate",
                "approve",
                "assign",
                "confirm"
              ]
            }
          ]
        }
      ]
    }
  ]
}